package memory

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	"github.com/OrdoAI/yuri-agent/internal/domain"
)

var (
	ErrNoStore           = errors.New("memory: store is not configured")
	ErrNoArchiveSearch   = errors.New("memory: archive search is not configured")
	ErrNoEmbedder        = errors.New("memory: embedder is not configured")
	ErrNoQuery           = errors.New("memory: query is required")
	ErrBudgetExceeded    = errors.New("memory: context budget exceeded")
	ErrCandidateRejected = errors.New("memory: candidate rejected")
)

// Store is the authoritative persistence boundary for memory records.  The
// ApplyMemoryChange operation is intentionally atomic: implementations must
// commit the current projection, append-only revision, and immutable sources
// as one transaction.  A lost vector/FTS index may be rebuilt from this
// boundary and must never lose a memory.
type Store interface {
	GetMemory(context.Context, domain.ID) (Memory, error)
	ListMemories(context.Context, MemoryFilter) ([]Memory, error)
	ApplyMemoryChange(context.Context, MemoryChange) error
	TouchMemory(context.Context, domain.ID, time.Time) error
	ListMemorySources(context.Context, domain.ID) ([]MemorySource, error)
	ListMemoryVersions(context.Context, domain.ID, int) ([]MemoryRevision, error)
}

// LexicalSearcher is an optional FTS5 (or equivalent) projection.  Engine
// falls back to bounded in-memory lexical scoring when the adapter does not
// implement this port.  Results should carry a snippet generated by the
// authoritative content, never an executable instruction.
type LexicalSearcher interface {
	SearchMemoryLexical(context.Context, string, MemoryFilter, int) ([]LexicalHit, error)
}

type LexicalHit struct {
	MemoryID domain.ID `json:"memory_id"`
	Score    float64   `json:"score"`
	Snippet  string    `json:"snippet,omitempty"`
}

// ArchiveSearcher is deliberately separate from Store because the full
// transcript belongs to the conversation repository.  It is only called by
// deliberate on-demand recall and is never loaded into every prompt.
type ArchiveSearcher interface {
	SearchArchive(context.Context, string, ArchiveSearchOptions) ([]ArchiveHit, error)
}

// Extractor runs after a turn (usually in a background worker) and chooses
// whether anything deserves permanent storage.  Returning an empty slice is
// a successful, expected result.
type Extractor interface {
	Extract(context.Context, Turn) ([]Candidate, error)
}

// Embedder is an optional provider-neutral semantic projection.  Secrets and
// provider credentials stay outside this contract.  Version must be stable
// for a given embedding model/configuration so stale vectors can be rebuilt.
type Embedder interface {
	Embed(context.Context, []string) ([][]float64, error)
	Version() string
}

type VectorDocument struct {
	ID      domain.ID
	Vector  []float64
	Version string
}

type VectorMatch struct {
	ID    domain.ID
	Score float64
}

// VectorIndex is a derived index.  Implementations should be safe for
// concurrent reads/writes and tolerate an index rebuild after a crash.
type VectorIndex interface {
	Upsert(context.Context, VectorDocument) error
	Delete(context.Context, domain.ID) error
	Search(context.Context, []float64, int) ([]VectorMatch, error)
}

// Consolidator is a hook for a provider/model-assisted merge or conflict
// resolver.  The default implementation is deterministic and conservative;
// applications may inject a stronger resolver without changing Store.
type Consolidator interface {
	Consolidate(context.Context, Memory, Candidate) (Consolidation, error)
}

type Consolidation struct {
	Operation MemoryOperation
	Memory    Memory
	Reason    string
	Noop      bool
}

// Clock and IDGenerator are small seams for deterministic tests.  If omitted
// by callers, time.Now and domain.RandomIDGenerator are used.
type Clock func() time.Time

type IDGenerator interface {
	NewID(string) (domain.ID, error)
}

func contextErr(ctx context.Context) error {
	if ctx == nil {
		return fmt.Errorf("%w: nil context", domain.ErrInvalidArgument)
	}
	select {
	case <-ctx.Done():
		return ctx.Err()
	default:
		return nil
	}
}

func defaultNow() time.Time { return time.Now().UTC() }

func normalizeQuery(query string) (string, error) {
	query = strings.TrimSpace(query)
	if query == "" {
		return "", fmt.Errorf("%w: empty query", ErrNoQuery)
	}
	return query, nil
}
